### ISSUE TITLE
Secondary Rate Limits

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/cloudflare-deploy-action#19]
Been getting this a lot. We need to run `Find associated pull request` with authentication. We can authenticate as our app as we do in some of the other CI/CD.

```sh
Run ubiquity/cloudflare-deploy-action@main
Run actions/setup-node@v4
Attempting to download 20.10.0...
Acquiring 20.10.0 - x64 from https://github.com/actions/node-versions/releases/download/20.10.0-6972104774/node-20.10.0-linux-x64.tar.gz
Extracting ...
/usr/bin/tar xz --strip 1 --warning=no-unknown-keyword --overwrite -C /home/runner/work/_temp/02ddd055-ac64-455c-a47e-8689c59c5216 -f /home/runner/work/_temp/8609a306-01ae-4aa8-a7d3-bf05bcc491dd
Adding to the cache ...
Environment details
Run actions/github-script@v7
  with:
    script: const response = await github.rest.search.issuesAndPullRequests({
    q: 'repo:ubiquity/work.ubq.fi is:pr sha:02fc36d24c14d68f65d0fca6b7abaa022a2980e9',
    per_page: 1,
  })
  const items = response.data.items
  if (items.length < 1) {
    console.error('No PRs found')
    return {forcePreviewDeploy: false, pullRequestNumber: null }
  }
  const pullRequestNumber = items[0].number
  const forcePreviewDeploy = pullRequestNumber > 0  && items[0].pull_request.merged_at == null
  console.info("Pull request number is", pullRequestNumber)
  console.info("forcePreviewDeploy", forcePreviewDeploy)
  return {forcePreviewDeploy: forcePreviewDeploy, pullRequestNumber: pullRequestNumber }
  
    github-token: ***
    debug: false
    user-agent: actions/github-script
    result-encoding: json
    retries: 0
    retry-exempt-status-codes: 400,401,403,404,422
RequestError [HttpError]: You have exceeded a secondary rate limit. Please wait a few minutes before you try again. If you reach out to GitHub Support for help, please include the request ID 2410:34C107:144A7C4:27B0A69:66FAB445.
    at /home/runner/work/_actions/actions/github-script/v7/dist/index.js:9537:21
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v7/dist/index.js:35424:16), <anonymous>:3:[18](https://github.com/ubiquity/work.ubq.fi/actions/runs/11108125855/job/30860345343#step:2:20))
    at async main (/home/runner/work/_actions/actions/github-script/v7/dist/index.js:35522:[20](https://github.com/ubiquity/work.ubq.fi/actions/runs/11108125855/job/30860345343#step:2:22)) {
  status: 403,
  response: {
    url: 'https://api.github.com/search/issues?q=repo%3Aubiquity%2Fwork.ubq.fi%20is%3Apr%20sha%3A02fc36d24c14d68f65d0fca6b7abaa022a2980e9&per_page=1',
    status: 403,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      'content-encoding': 'gzip',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Mon, 30 Sep 2024 14:23:01 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'github.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      'transfer-encoding': 'chunked',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-api-version-selected': '20[22](https://github.com/ubiquity/work.ubq.fi/actions/runs/11108125855/job/30860345343#step:2:24)-11-28',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': '2410:34C107:144A7C4:[27](https://github.com/ubiquity/work.ubq.fi/actions/runs/11108125855/job/30860345343#step:2:30)B0A69:66FAB445',
      'x-ratelimit-limit': '30',
      'x-ratelimit-remaining': '[29](https://github.com/ubiquity/work.ubq.fi/actions/runs/11108125855/job/30860345343#step:2:32)',
      'x-ratelimit-reset': '1727706241',
      'x-ratelimit-resource': 'search',
      'x-ratelimit-used': '1',
      'x-xss-protection': '0'
    },
    data: {
      documentation_url: 'https://docs.github.com/free-pro-team@latest/rest/overview/rate-limits-for-the-rest-api#about-secondary-rate-limits',
      message: 'You have exceeded a secondary rate limit. Please wait a few minutes before you try again. If you reach out to GitHub Support for help, please include the request ID 2410:[34](https://github.com/ubiquity/work.ubq.fi/actions/runs/11108125855/job/30860345343#step:2:37)C107:144A7C4:27B0A69:66FAB445.'
    }
  },
  request: {
    method: 'GET',
    url: 'https://api.github.com/search/issues?q=repo%3Aubiquity%2Fwork.ubq.fi%20is%3Apr%20sha%3A02fc[36](https://github.com/ubiquity/work.ubq.fi/actions/runs/11108125855/job/30860345343#step:2:39)d24c14d68f65d0fca6b7abaa022a2980e9&per_page=1',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'actions/github-script octokit-core.js/5.0.1 Node.js/20.13.1 (linux; x64)',
      authorization: 'token [REDACTED]'
    },
    request: {
      agent: [Agent],
      fetch: [Function: proxyFetch],
      hook: [Function: bound bound register]
    }
  }
}
Error: Unhandled error: HttpError: You have exceeded a secondary rate limit. Please wait a few minutes before you try again. If you reach out to GitHub Support for help, please include the request ID 2[41](https://github.com/ubiquity/work.ubq.fi/actions/runs/11108125855/job/30860345343#step:2:44)0:34C107:144A7C4:27B0A69:66FAB445.
```

From https://github.com/ubiquity/work.ubq.fi/actions/runs/11108125855/job/30860345343

**Comment by 0x4007** [comment]
Unfortunately I realized the best solution is to pass in the `APP_ID` and `APP_PRIVATE_KEY` secrets from within every repository's action. That means I need to push changes to all of them. The alternative is I hard code an app's credentials in here so that we can get higher rate limits.

**Comment by 0x4007** [comment]
Just added to ts-template so hopefully it syncs and we can add authentication to all repo deploys!

**Comment by 0x4007** [comment]
@gentlementlegen

This should have thrown a failure https://github.com/ubiquity-os-marketplace/conversation-rewards/actions/runs/11108830072/job/30862713555

**Comment by gentlementlegen** [comment]
@0x4007 That's one hell of a reward lol. I guess it counted the content within the `code` which should not have happened, I can look into it. Edit 2: it is not using the latest changes that got merged regarding the rewards.

It didn't throw because technically the configuration defaulted to a valid version omitting the invalid parts. We cannot throw otherwise we cannot disable modules partially within this plugin, which is why it was acting this way.

**Comment by 0x4007** [comment]
Yeah the old count is broken cause of the code inside the code block. I am trying to use a different version of the plugin now.

**Comment by gentlementlegen** [comment]
@0x4007 Since you moved everything to `main` we have to start merging things into the main branch again.

**Comment by 0x4007** [comment]
I'm deciding the lesser of evils. Its nice to use an organization to fully test production (kernel and plugins) and then other orgs to test development.

We could set a weekly cron to semver and merge to main maybe

**Comment by gentlementlegen** [comment]
@0x4007 Here you go, seems to make much more sense.

**Comment by 0x4007** [comment]
Formatting in analytics should total the score correctly. This is not rendering the correct number.

**Comment by gentlementlegen** [comment]
That's a new, will have a look. Too many manual merges happened recently.

**Comment by 0x4007** [comment]
Specifically it looks like its not including the "word counter" in the formatting overview score.

**Comment by gentlementlegen** [comment]
Hard to tell but that's possible. Since the regex have been deleted and taken out on a higher level the parser might not pick it up.

**Comment by gentlementlegen** [comment]
Adding some `content` to test the results:
```
content
```
- content 1
- content 2
- content 3
